### ISSUE TITLE
Sign in doesn't find my blog site

### ISSUE THREAD

**Issue by StephenLasseter** [jacobsokora/Ghost-Publisher#2]
Ghost Publisher version 0.0.3
iPhone 8 Plus running iOS 13.4.1
Ghost blog running from the docker-hub image version 3.13.4 (latest)

I'm trying to access my internal blog.  Let's say the address is:
`http://example.home.cooldomainname.net`

The result in red is 
> Ghost site not found

This same url works fine from the same phone on safari.  The phone is on the same network as the server with the blog.  Is it because I'm not running https on that server?  I also tried tacking `/ghost` to the end, but no success.

**Comment by willowsokora** [comment]
@StephenLasseter Can you please give me the domain of your blog so I can do some testing on my end? Also, can you elaborate on what you mean by “internal”?

If you don't want to share your blog url, please tell me what response you get from BLOG_URL/ghost/api/v3/admin/site

**Comment by willowsokora** [comment]
I just noticed you said you're not running https, that may be the issue. Apple doesn't allow insecure connections from apps, there was a workaround at one point, but I believe they've put a hard stop on it.

**Comment by StephenLasseter** [comment]
> I just noticed you said you're not running https, that may be the issue. Apple doesn't allow insecure connections from apps, there was a workaround at one point, but I believe they've put a hard stop on it.

Ahhhh, that sounds like a good lead.  I'll look into what I can do for a cert in this scenario and report back.

**Comment by willowsokora** [comment]
Wish I could do more, but I will add a note in the next version about this, and disallow insecure blog urls from being accepted
