### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by vidalpascual** [jacobsokora/Ghost-Publisher#4]
Hi,

I can't log in my blog. Email and password are correct. Can you help me?

![error](https://user-images.githubusercontent.com/3727107/95355557-f829ca80-08c5-11eb-916b-469c2d64ae7a.jpg)

Regards

**Comment by dallasgroot** [comment]
were you able to log in? i'm on Ghost V4 and logged in just fine.

**Comment by vidalpascual** [comment]
Yes, I can. I think it was a certificate issue.

**Comment by vidalpascual** [comment]
Thanks!
